'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDownToLine, Box, Check, ExternalLink, Languages, Layers3, LoaderCircle, Minus, PackagePlus, Plus, RefreshCw, Search, Trash2, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { detectLocale, formatText, localeNames, locales, Locale, TranslationKey, translations } from './i18n';

type CardItem = { id:number; productId:number; name:string; itemType:'card'|'sealed'; printing:string; quantity:number; marketPrice:number|null; updatedAt:string|null };
type ApiData = { items?:CardItem[]; updated?:number; error?:string; errorCode?:string };
const getProductId = (value:string) => Number(value.match(/(?:product\/)?(\d{4,})/)?.[1] || NaN);
const errorKeys: Record<string, TranslationKey> = { AUTH_REQUIRED:'authRequired', INCOMPLETE:'incomplete', INVALID_ADJUSTMENT:'invalidAdjustment', NOT_FOUND:'notFound', INVALID_ID:'invalidId' };

export default function InventoryClient({user,signOutPath}:{user:{displayName:string;email:string};signOutPath:string}) {
  const [locale,setLocale] = useState<Locale>('zh-CN');
  const [items,setItems] = useState<CardItem[]>([]); const [loading,setLoading]=useState(true); const [syncing,setSyncing]=useState(false); const [adding,setAdding]=useState(false); const [query,setQuery]=useState(''); const [message,setMessage]=useState('');
  const [form,setForm]=useState({link:'',name:'',itemType:'card' as 'card'|'sealed',printing:'Foil',quantity:'1'});
  const t=translations[locale]; const rtl=locale==='ar'; const dir=rtl?'rtl':'ltr';
  const usd=useMemo(()=>new Intl.NumberFormat(locale,{style:'currency',currency:'USD',minimumFractionDigits:2}),[locale]);
  const number=useMemo(()=>new Intl.NumberFormat(locale),[locale]);
  const tr=(key:TranslationKey,values?:Record<string,string|number>)=>formatText(t[key],values);
  const apiError=(data:ApiData,fallback:TranslationKey)=>data.errorCode&&errorKeys[data.errorCode]?t[errorKeys[data.errorCode]]:t[fallback];

  useEffect(()=>{const saved=localStorage.getItem('card-vault-locale') as Locale|null;setLocale(saved&&locales.includes(saved)?saved:detectLocale())},[]);
  useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=dir;localStorage.setItem('card-vault-locale',locale)},[locale,dir]);
  const loadInventory=useCallback(async()=>{try{const r=await fetch('/api/inventory');if(!r.ok)throw new Error();setItems(((await r.json()) as {items:CardItem[]}).items)}catch{setMessage(translations[locale].readFailed)}finally{setLoading(false)}},[locale]);
  const refreshPrices=useCallback(async(force=false)=>{setSyncing(true);setMessage('');try{const r=await fetch('/api/prices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({force})});const d=await r.json() as ApiData;if(!r.ok)throw new Error(apiError(d,'priceFailed'));if(d.items)setItems(d.items);setMessage(d.updated?tr('updatedPrices',{count:number.format(d.updated)}):t.pricesCurrent)}catch(e){setMessage(e instanceof Error?e.message:t.priceFailed)}finally{setSyncing(false)}},[locale,number,t]);
  useEffect(()=>{void loadInventory().then(()=>refreshPrices(false))},[loadInventory,refreshPrices]);

  async function addItem(e:FormEvent){e.preventDefault();const productId=getProductId(form.link);if(!form.link.trim()){setMessage(t.pasteLink);return}if(!productId){setMessage(t.invalidProductId);return}if(!form.name.trim()){setMessage(t.enterName);return}setAdding(true);setMessage('');try{const r=await fetch('/api/inventory',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId,name:form.name.trim(),itemType:form.itemType,printing:form.itemType==='sealed'?'Sealed':form.printing.trim()||'Foil',quantity:Math.max(1,Number(form.quantity)||1)})});const d=await r.json() as ApiData;if(!r.ok)throw new Error(apiError(d,'addFailed'));if(d.items)setItems(d.items);setForm({link:'',name:'',itemType:'card',printing:'Foil',quantity:'1'});setMessage(t.added);await refreshPrices(true)}catch(error){setMessage(error instanceof Error?error.message:t.addFailed)}finally{setAdding(false)}}
  async function removeItem(id:number){const r=await fetch(`/api/inventory?id=${id}`,{method:'DELETE'});if(r.ok)setItems(c=>c.filter(i=>i.id!==id));else setMessage(t.notFound)}
  async function changeQuantity(id:number,delta:1|-1){const current=items.find(i=>i.id===id);if(!current||(delta<0&&current.quantity<=1))return;setItems(list=>list.map(i=>i.id===id?{...i,quantity:i.quantity+delta}:i));try{const r=await fetch('/api/inventory',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,delta})});const d=await r.json() as ApiData;if(!r.ok)throw new Error(apiError(d,'quantityFailed'));if(d.items)setItems(d.items)}catch(error){setItems(list=>list.map(i=>i.id===id?{...i,quantity:i.quantity-delta}:i));setMessage(error instanceof Error?error.message:t.quantityFailed)}}
  const filtered=useMemo(()=>{const n=query.trim().toLowerCase();return n?items.filter(i=>i.name.toLowerCase().includes(n)||String(i.productId).includes(n)):items},[items,query]);
  const totals=useMemo(()=>{const market=items.reduce((s,i)=>s+(i.marketPrice||0)*i.quantity,0);return{copies:items.reduce((s,i)=>s+i.quantity,0),market,cash:market*.8}},[items]);
  const latest=items.map(i=>i.updatedAt).filter(Boolean).sort().at(-1);
  function exportCsv(){const rows=[[t.csvName,'Product ID',t.csvType,t.csvPrinting,t.csvQuantity,t.csvMarket,t.csvCash],...items.map(i=>[i.name,i.productId,i.itemType==='sealed'?t.sealed:t.card,i.printing,i.quantity,i.marketPrice??'',((i.marketPrice||0)*i.quantity*.8).toFixed(2)])];const csv=rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='pokemon-inventory.csv';a.click();URL.revokeObjectURL(a.href)}

  return <main className="min-h-screen pb-14" dir={dir}>
    <header className="border-b border-white/10 bg-[#101521]/92 text-white backdrop-blur-xl"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-3 px-5 py-4 md:px-10"><div className="flex items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#f4ca47] text-[#171b26] shadow-[0_0_0_5px_rgba(244,202,71,.09)]"><WalletCards className="size-5"/></span><div><p className="font-display text-lg font-bold tracking-tight">{t.vault}</p><p className="text-xs text-slate-400">{t.subtitle}</p></div></div><div className="flex items-center gap-2 sm:gap-3"><div className="hidden items-center gap-2 text-xs text-slate-300 xl:flex"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]"/>{t.marketUsd}</div><div className="relative"><Languages className={`pointer-events-none absolute top-1/2 size-3.5 -translate-y-1/2 text-slate-400 ${rtl?'right-2.5':'left-2.5'}`}/><select aria-label={t.language} value={locale} onChange={e=>setLocale(e.target.value as Locale)} className={`h-9 appearance-none rounded-lg border border-white/15 bg-white/5 text-xs font-semibold text-slate-200 outline-none hover:border-white/30 ${rtl?'pr-8 pl-3':'pl-8 pr-3'}`}>{locales.map(code=><option key={code} value={code} className="bg-[#171d2b]">{localeNames[code]}</option>)}</select></div><div className="hidden h-5 w-px bg-white/15 sm:block"/><div className="hidden min-w-0 text-end md:block"><p className="max-w-40 truncate text-xs font-semibold text-slate-200">{user.displayName}</p><p dir="ltr" className="hidden max-w-48 truncate text-[11px] text-slate-500 lg:block">{user.email}</p></div><a href={signOutPath} target="_top" className="whitespace-nowrap rounded-lg border border-white/15 px-3 py-2 text-xs font-semibold text-slate-300 hover:border-white/30 hover:text-white">{t.signOut}</a></div></div></header>
    <div className="mx-auto max-w-[1440px] px-5 pt-8 md:px-10">
      <section className="mb-7 grid gap-4 lg:grid-cols-[1.35fr_.65fr_.65fr]">
        <div className="relative overflow-hidden rounded-[26px] bg-[#171d2b] p-6 text-white shadow-[0_22px_60px_rgba(20,29,45,.14)] md:p-8"><div className="pokeball-grid absolute inset-0 opacity-20"/><div className="relative"><p className="mb-5 text-xs font-semibold uppercase tracking-[.22em] text-[#f4ca47]">{t.currentCollection}</p><p dir="ltr" className={`font-display text-4xl font-bold tracking-[-.04em] md:text-5xl ${rtl?'text-right':''}`}>{usd.format(totals.market)}</p><div className="mt-5 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-slate-300"><span>{number.format(totals.copies)} {t.cards}</span><span className="h-4 w-px bg-white/15"/><span>{number.format(items.length)} {t.itemCount}</span><span className="h-4 w-px bg-white/15"/><span>{t.cashRate}</span></div></div></div>
        <div className="metric-card border-[#f4ca47]"><p className="metric-label">{t.cashValue}</p><p dir="ltr" className={`metric-value ${rtl?'text-right':''}`}>{usd.format(totals.cash)}</p><p className="metric-note">{t.marketTimes}</p></div>
        <div className="metric-card border-emerald-400"><p className="metric-label">{t.dataStatus}</p><p className="metric-value text-[1.7rem]">{syncing?t.syncing:latest?t.updated:t.pending}</p><p className="metric-note">{latest?new Date(latest).toLocaleString(locale,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):t.autoCheck}</p></div>
      </section>
      <section className="grid items-start gap-6 xl:grid-cols-[360px_minmax(0,1fr)]">
        <aside className="panel xl:sticky xl:top-6"><div className="panel-heading"><div><p className="eyebrow">{t.addEyebrow}</p><h1>{t.addTitle}</h1></div><span className="icon-chip"><PackagePlus/></span></div>
          <form className="space-y-4" onSubmit={addItem}><div><span className="field-label">{t.inventoryType}</span><div className="mt-2 grid grid-cols-2 gap-2 rounded-xl bg-slate-100 p-1"><button type="button" className={`type-option ${form.itemType==='card'?'type-option-active':''}`} onClick={()=>setForm({...form,itemType:'card'})}><Layers3/>{t.card}</button><button type="button" className={`type-option ${form.itemType==='sealed'?'type-option-active':''}`} onClick={()=>setForm({...form,itemType:'sealed'})}><Box/>{t.sealed}</button></div></div><label className="field-label">{t.linkLabel}<Input dir="ltr" className="field-input text-start" placeholder={t.linkPlaceholder} value={form.link} onChange={e=>setForm({...form,link:e.target.value})}/></label><label className="field-label">{form.itemType==='sealed'?t.productName:t.cardName}<Input className="field-input" placeholder={form.itemType==='sealed'?t.productPlaceholder:t.cardPlaceholder} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className={`grid gap-3 ${form.itemType==='sealed'?'grid-cols-1':'grid-cols-[1fr_96px]'}`}>{form.itemType==='card'&&<label className="field-label">{t.printing}<Input className="field-input" placeholder="Foil" value={form.printing} onChange={e=>setForm({...form,printing:e.target.value})}/></label>}<label className="field-label">{t.quantity}<Input className="field-input" min="1" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label></div><Button type="submit" className="h-11 w-full rounded-xl bg-[#f4ca47] font-bold text-[#191d27] hover:bg-[#ffda64]" disabled={adding}>{adding?<LoaderCircle className="animate-spin"/>:<PackagePlus/>}{t.addAndPrice}</Button></form>
          <div className="mt-5 rounded-2xl border border-amber-200/70 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><span className="mb-2 flex items-center gap-2 font-bold"><Check className="size-3.5"/>{t.tip}</span>{form.itemType==='sealed'?t.sealedTip:t.cardTip}</div>
        </aside>
        <section className="panel min-w-0"><div className="panel-heading gap-4 max-md:flex-col max-md:items-start"><div><p className="eyebrow">{t.inventoryEyebrow}</p><h2>{t.inventoryTitle}</h2></div><div className="flex w-full flex-1 items-center justify-end gap-2 md:w-auto"><div className="relative w-full max-w-64"><Search className={`absolute top-1/2 size-4 -translate-y-1/2 text-slate-400 ${rtl?'right-3':'left-3'}`}/><Input aria-label={t.searchInventory} className={`h-10 rounded-xl bg-slate-50 ${rtl?'pr-9':'pl-9'}`} placeholder={t.searchPlaceholder} value={query} onChange={e=>setQuery(e.target.value)}/></div><Button aria-label={t.updateNow} className="h-10 rounded-xl" variant="outline" onClick={()=>refreshPrices(true)} disabled={syncing||items.length===0}><RefreshCw className={syncing?'animate-spin':''}/><span className="hidden sm:inline">{t.updatePrices}</span></Button></div></div>
          {message&&<output className="mb-4 block rounded-xl bg-slate-100 px-4 py-3 text-sm text-slate-600">{message}</output>}
          <div className="overflow-x-auto rounded-2xl border border-slate-200"><Table><TableHeader className="bg-[#f7f8fa]"><TableRow><TableHead className="ps-4">{t.product}</TableHead><TableHead>{t.typePrinting}</TableHead><TableHead className="text-center">{t.quantity}</TableHead><TableHead className="text-end">{t.tcgPrice}</TableHead><TableHead className="text-end">{t.totalMarket}</TableHead><TableHead className="bg-amber-50 text-end text-amber-900">{t.cashValue80}</TableHead><TableHead className="w-12"/></TableRow></TableHeader><TableBody>
            {loading?<TableRow><TableCell colSpan={7} className="h-40 text-center text-slate-400"><LoaderCircle className="mx-auto mb-2 animate-spin"/>{t.loading}</TableCell></TableRow>:filtered.length===0?<TableRow><TableCell colSpan={7} className="h-48 text-center"><WalletCards className="mx-auto mb-3 size-8 text-slate-300"/><p className="font-semibold text-slate-600">{items.length?t.noMatches:t.emptyVault}</p><p className="mt-1 text-xs text-slate-400">{t.addFirst}</p></TableCell></TableRow>:filtered.map(item=>{const total=(item.marketPrice||0)*item.quantity;return <TableRow key={item.id} className="group"><TableCell className="ps-4"><div className="flex items-center gap-3"><img className={`rounded-md object-contain shadow-sm ${item.itemType==='sealed'?'h-14 w-14 bg-white':'h-14 w-10'}`} src={`https://tcgplayer-cdn.tcgplayer.com/product/${item.productId}_200w.jpg`} alt=""/><div dir="auto"><a className="flex items-center gap-1 font-semibold text-[#182033] hover:text-blue-600" href={`https://www.tcgplayer.com/product/${item.productId}`} target="_blank" rel="noreferrer">{item.name}<ExternalLink className="size-3 opacity-50"/></a><p dir="ltr" className="mt-1 font-mono text-[11px] text-slate-400">#{item.productId}</p></div></div></TableCell><TableCell><span className={`rounded-full px-2.5 py-1 text-xs ${item.itemType==='sealed'?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-600'}`}>{item.itemType==='sealed'?t.sealed:item.printing}</span></TableCell><TableCell><div dir="ltr" className="mx-auto flex w-fit items-center rounded-lg border border-slate-200 bg-white p-0.5 shadow-sm"><Button type="button" aria-label={tr('decrease',{name:item.name})} title={item.quantity<=1?t.minQuantity:t.decreaseOne} variant="ghost" size="icon-xs" disabled={item.quantity<=1} onClick={()=>changeQuantity(item.id,-1)}><Minus/></Button><span className="min-w-8 px-1 text-center font-semibold tabular-nums">{number.format(item.quantity)}</span><Button type="button" aria-label={tr('increase',{name:item.name})} title={t.increaseOne} variant="ghost" size="icon-xs" onClick={()=>changeQuantity(item.id,1)}><Plus/></Button></div></TableCell><TableCell dir="ltr" className="text-end tabular-nums">{item.marketPrice==null?<span className="text-slate-400">{t.pendingPrice}</span>:usd.format(item.marketPrice)}</TableCell><TableCell dir="ltr" className="text-end font-semibold tabular-nums">{usd.format(total)}</TableCell><TableCell dir="ltr" className="bg-amber-50/60 text-end font-bold tabular-nums text-amber-900">{usd.format(total*.8)}</TableCell><TableCell><Button type="button" aria-label={tr('deleteItem',{name:item.name})} title={t.deleteTitle} variant="ghost" size="icon" className="text-slate-300 opacity-0 group-hover:opacity-100 hover:text-red-500 focus:opacity-100" onClick={()=>removeItem(item.id)}><Trash2/></Button></TableCell></TableRow>})}
          </TableBody></Table></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-400"><p>{t.priceDisclaimer}</p><button className="flex items-center gap-1.5 font-semibold text-slate-500 hover:text-slate-800" onClick={exportCsv}><ArrowDownToLine className="size-3.5"/>{t.exportCsv}</button></div>
        </section>
      </section>
    </div>
  </main>
}
